#!/bin/bash
composer create-project laravel/laravel --prefer-dist hello

cd hello

git init

git add .

git commit -m "new laravel project"

echo web: vendor/bin/heroku-php-apache2 public/ > Procfile

git add .

git commit -m "Procfile for Heroku"

heroku create

heroku config:set APP_KEY=$(php artisan --no-ansi key:generate --show)

git push heroku master

heroku open
